name: Generate and Commit README
on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main # Remplacez "main" par la branche sur laquelle vous souhaitez déclencher l'action

jobs:
  generate_and_commit_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Changer la version de Node.js si nécessaire

      - name: Install dependencies
        run: npm install

      - name: Generate README.md
        run: node generateReadme.js

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "thomas.gauzin@gmail.com" # Remplacez par votre adresse e-mail GitHub
          git config --local user.name "Casblitel"
          git add README.md
          git commit -m "Update README.md"
          git push origin main
