name: Update README

on:
  push:
    branches:
      - main

  # Déclenche le workflow tous les jours à huit heures UTC ;
  # minutes / heures / jours du mois / mois / jours de la semaine.
  schedule:
    - cron: "0 8 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Use the Node.js version you prefer

      - name: Install dependencies
        run: npm install

      - name: Run generateReadme.js
        run: node generateReadme.js

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README.md" || true

      - name: Push changes
        uses: softprops/action-gh-pages@v3
        with:
          branch: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
